/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    App: typeof import('./App.vue')['default']
    Button: typeof import('./core/components/Button.vue')['default']
    ConfigPanel: typeof import('./core/layouts/components/Header/ConfigPanel.vue')['default']
    Dashboard: typeof import('./pages/Dashboard.vue')['default']
    Header: typeof import('./core/layouts/components/Header/Header.vue')['default']
    Home: typeof import('./core/layouts/templates/Home.vue')['default']
    Icon: typeof import('./core/components/Icon.vue')['default']
    PermissionList: typeof import('./modules/security/permission/views/PermissionList.vue')['default']
    RoleList: typeof import('./modules/security/role/views/RoleList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./core/layouts/components/Sidebar/Sidebar.vue')['default']
    UserList: typeof import('./modules/security/user/views/UserList.vue')['default']
  }
}
